### ISSUE TITLE
Enable charts to provide default location configuration

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#29]
Consider the case of installing a system wide prometheus chart and wanting it to be in a well known location. A Helm repository owner can craft a set of charts with default configuration that can be overridden for name and namespace. These would be specified using annotations in the chart:

```yaml
annotations:
  catalog.cattle.io/namespace: fleet-system
  catalog.cattle.io/release-name: fleet
```

This example is pulled from Ranchers own charts.

`hypper install` would need to take the name as a flag or optional argument where the flag or argument would override the default specified in the chart.

**Comment by mattfarina** [comment]
After out call today with Darren I want to add the detail of:

On install use the annotations to get the name (a.k.a release name) and namespace to use for installation.

There are hypper annotations to use for these along with Rancher catalog fallback annotations. The hypper ones are:

```yaml
annotations:
  hypper.cattle.io/namespace: fleet-system
  hypper.cattle.io/release-name: fleet
```

The catalog fallback ones are:

```yaml
annotations:
  catalog.cattle.io/namespace: fleet-system
  catalog.cattle.io/release-name: fleet
```

The priority order for namespace should be:

1. The flag passed in from the CLI
2. The `hypper.cattle.io/namespace` annotation
3. The `catalog.cattle.io/namespace` annotation
4. The current namespace as configured with the kubeconfig (when no information is given). This is what Helm does when no namespace is passed in by the flag.

In Helm there is an argument for the name (unless `--generate-name` is set). Hypper will change from this.

The priority order for name should be:

1. The argument passed in from the CLI
2. The `hypper.cattle.io/release-name` annotation
3. The `catalog.cattle.io/release-name` annotation
4. `--generate-name`
5. An error as Helm does today

The name and namespace used should be set to output at an info level. We want this see all of the time.

For dev/test purposes you can use the current rancher catalog charts. The repository is at https://charts.rancher.io. It uses the annotation prefix of `catalog.cattle.io`.
