### ISSUE TITLE
Shared Dependencies

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#30]
Those who setup Helm repos can have a collection of Helm charts that install and work together. But, they don't all need to be installed at the same time or together.

For example, there are two apps that independent of each other. But, you want both of them to work with a shared prometheus. In Helm, you would need to install prometheus. Then when installing the application know where prometheus is and pass in the configuration details.

This setup would enable a chart to specify the name and namespace to be installed into. This would be a default value to be used. Then other charts could specify the dependency they need, the name to look for, and the namespace to look in. If the dependency does not exist it should then be installed first. If it is installed than it can be used.

RBAC needs to be follows and if access is not available hypper should fail and notify users.

This issue only needs to deal with the installation of the shared dependencies. Configuring them to work together is a separate concern.

Requiring a shared dependency can be captured in Helm chart annotations like:

```yaml
annotations:
  hypper.cattle.io/shared-dependencies: |
   - name: bar            # Chart instance name in the namespace
     namespace: default   # The namespace to look in
     chart: foo           # The name of the chart
     version: ^1.2.3      # A version range of supported versions
```

Installing to a common location is covered in #29.
