### ISSUE TITLE
Add global registry automatically

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#63]
Rancher adds a couple global values to charts by default that should be added automatically. We can start with the global registry:

```yaml
global:
  cattle:
    systemDefaultRegistry: ""
```

This provides a default registry that can be used by charts to know where the container images are at. This is especially useful for on-premise setups.

This does mean we need to work out a way to capture this piece of information
